# Generated by Django 3.1.1 on 2020-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_date', models.DateTimeField(auto_created=True, default=None)),
                ('hire_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('fraction', models.IntegerField()),
                ('base', models.IntegerField()),
                ('advance', models.IntegerField()),
            ],
        ),
    ]
